/* Generated by tools/generate_gx_fifo.py from port/engine/gx.c. Do not edit. */
#ifndef MP_GX_FIFO_OPS_H
#define MP_GX_FIFO_OPS_H
enum{GXOP_WRAP=1,GXOP_BYTES,GXOP_FRAME_END,GXOP_STEREO,GXOP_LIST,GXOP_LIST_INLINE,GXOP_DC_RANGE,
    GXOP_INIT,GXOP_LEFT_CAPTURE,GXOP_COPY_YSCALE,
    GXOP_mp_gx_source_write,
    GXOP_mp_gx_invalidate_sources,
    GXOP_GXSetMisc,
    GXOP_GXInvalidateVtxCache,
    GXOP_GXInvalidateTexAll,
    GXOP_mp_gx_frame_texture_visibility,
    GXOP_GXSetTevClampMode,
    GXOP_GXSetLineWidth,
    GXOP_GXSetPointSize,
    GXOP_GXEnableTexOffsets,
    GXOP_GXSetTevColorS10,
    GXOP_GXSetTevSwapModeTable,
    GXOP_GXSetNumIndStages,
    GXOP_GXSetTevDirect,
    GXOP_GXSetIndTexOrder,
    GXOP_GXSetIndTexCoordScale,
    GXOP_GXSetIndTexMtx,
    GXOP_GXSetTevIndirect,
    GXOP_GXSetFog,
    GXOP_GXSetFogRangeAdj,
    GXOP_GXSetPixelFmt,
    GXOP_GXSetFieldMode,
    GXOP_GXSetZTexture,
    GXOP_GXSetDispCopySrc,
    GXOP_GXSetDispCopyDst,
    GXOP_GXSetCopyClear,
    GXOP_GXSetCopyClamp,
    GXOP_GXSetDispCopyGamma,
    GXOP_GXSetCopyFilter,
    GXOP_GXSetTexCopySrc,
    GXOP_GXSetTexCopyDst,
    GXOP_GXCopyDisp,
    GXOP_mp_gx_copy_mode,
    GXOP_GXCopyTex,
    GXOP_mp_gx_copy_texture_only,
    GXOP_mp_gx_copy_clear_only,
    GXOP_mp_gx_display_width,
    GXOP_mp_gx_camera_convergence,
    GXOP_mp_gx_texture_mips,
    GXOP_GXBegin,
    GXOP_GXClearVtxDesc,
    GXOP_GXSetVtxDesc,
    GXOP_GXSetVtxAttrFmt,
    GXOP_GXSetArray,
    GXOP_GXSetCurrentMtx,
    GXOP_GXLoadPosMtxImm,
    GXOP_GXLoadNrmMtxImm,
    GXOP_GXLoadTexMtxImm,
    GXOP_GXSetProjection,
    GXOP_GXSetProjectionv,
    GXOP_GXSetViewport,
    GXOP_GXSetViewportJitter,
    GXOP_GXSetScissor,
    GXOP_GXSetCullMode,
    GXOP_GXSetZMode,
    GXOP_GXSetBlendMode,
    GXOP_GXSetChanMatColor,
    GXOP_GXSetChanAmbColor,
    GXOP_GXSetChanCtrl,
    GXOP_GXSetNumChans,
    GXOP_GXSetNumTexGens,
    GXOP_GXSetNumTevStages,
    GXOP_GXSetTexCoordGen2,
    GXOP_GXSetTevOrder,
    GXOP_GXSetTevColorIn,
    GXOP_GXSetTevAlphaIn,
    GXOP_GXSetTevColorOp,
    GXOP_GXSetTevAlphaOp,
    GXOP_GXSetTevSwapMode,
    GXOP_GXSetTevKColorSel,
    GXOP_GXSetTevKAlphaSel,
    GXOP_GXSetTevOp,
    GXOP_GXSetTevColor,
    GXOP_GXSetTevKColor,
    GXOP_GXSetColorUpdate,
    GXOP_GXSetAlphaUpdate,
    GXOP_GXSetDstAlpha,
    GXOP_GXSetDither,
    GXOP_GXSetZCompLoc,
    GXOP_GXSetAlphaCompare,
    GXOP_GXPixModeSync,
    GXOP_GXLoadTexObj,
    GXOP_GXLoadTlut,
    GXOP_GXLoadLightObjImm,GXOP_COUNT};
void gxr_mp_gx_source_write(const void*p,unsigned n);
void gxr_mp_gx_invalidate_sources(void);
void gxr_mp_gx_configure_cache(unsigned bytes);
GXFifoObj* gxr_GXInit(void*base,u32 size);
void gxr_GXSetMisc(GXMiscToken t,u32 value);
void gxr_GXInvalidateVtxCache(void);
void gxr_GXInvalidateTexAll(void);
void gxr_mp_gx_frame_texture_visibility(void);
void gxr_GXSetTevClampMode(int a,int b);
void gxr_GXSetLineWidth(u8 w,GXTexOffset x);
void gxr_GXSetPointSize(u8 w,GXTexOffset x);
void gxr_GXEnableTexOffsets(GXTexCoordID id,u8 a,u8 b);
u32 gxr_GXGetTexBufferSize(u16 w,u16 h,u32 fmt,u8 mip,u8 lod);
u16 gxr_GXGetTexObjWidth(const GXTexObj*o);
u16 gxr_GXGetTexObjHeight(const GXTexObj*o);
GXTexFmt gxr_GXGetTexObjFmt(const GXTexObj*o);
void gxr_GXGetViewportv(float*out);
void gxr_GXProject(float x,float y,float z,float m[3][4],float*p,float*v,float*sx,float*sy,float*sz);
void gxr_GXSetTevColorS10(GXTevRegID id,GXColorS10 c);
void gxr_GXSetTevSwapModeTable(GXTevSwapSel id,GXTevColorChan r,GXTevColorChan g,GXTevColorChan b,GXTevColorChan a);
void gxr_GXSetNumIndStages(u8 n);
void gxr_GXSetTevDirect(GXTevStageID s);
void gxr_GXSetIndTexOrder(GXIndTexStageID id,GXTexCoordID coord,GXTexMapID map);
void gxr_GXSetIndTexCoordScale(GXIndTexStageID id,GXIndTexScale s,GXIndTexScale t);
void gxr_GXSetIndTexMtx(GXIndTexMtxID id,float m[2][3],s8 e);
void gxr_GXSetTevIndirect(GXTevStageID s,GXIndTexStageID id,GXIndTexFormat f,GXIndTexBiasSel b,GXIndTexMtxID m,GXIndTexWrap ws,GXIndTexWrap wt,GXBool add,GXBool lod,GXIndTexAlphaSel a);
void gxr_GXSetFog(GXFogType t,float s,float e,float n,float f,GXColor c);
void gxr_GXInitFogAdjTable(GXFogAdjTable*t,u16 w,float p[4][4]);
void gxr_GXSetFogRangeAdj(GXBool b,u16 c,GXFogAdjTable*t);
void gxr_GXSetPixelFmt(GXPixelFmt p,GXZFmt16 z);
void gxr_GXSetFieldMode(GXBool f,GXBool a);
void gxr_GXSetZTexture(GXZTexOp o,GXTexFmt f,u32 b);
void gxr_GXSetDispCopySrc(u16 x,u16 y,u16 w,u16 h);
void gxr_GXSetDispCopyDst(u16 w,u16 h);
u32 gxr_GXSetDispCopyYScale(float s);
void gxr_GXSetCopyClear(GXColor c,u32 z);
void gxr_GXSetCopyClamp(GXFBClamp c);
void gxr_GXSetDispCopyGamma(GXGamma g);
void gxr_GXSetCopyFilter(GXBool aa,const u8 p[12][2],GXBool vf,const u8 f[7]);
void gxr_GXSetTexCopySrc(u16 x,u16 y,u16 w,u16 h);
void gxr_GXSetTexCopyDst(u16 w,u16 h,GXTexFmt fmt,GXBool mip);
void gxr_GXCopyDisp(void*dest,GXBool clear);
void gxr_mp_gx_copy_mode(u32 mode);
GXDrawDoneCallback gxr_GXSetDrawDoneCallback(GXDrawDoneCallback cb);
void gxr_GXWaitDrawDone(void);
void gxr_GXSetDrawDone(void);
void gxr_GXCopyTex(void*dest,GXBool clear);
void gxr_mp_gx_copy_texture_only(void*dest,int clear);
void gxr_mp_gx_copy_clear_only(void*dest,int clear);
void gxr_GXDrawDone(void);
void gxr_mp_gx_display_width(unsigned width);
void gxr_mp_gx_camera_convergence(float convergence);
void gxr_mp_gx_texture_mips(unsigned enable);
unsigned gxr_mp_gx_left_capture(unsigned enabled);
void gxr_GXBegin(GXPrimitive type,GXVtxFmt fmt,u16 nverts);
void gxr_mp_gx_write_u8(u8 x);
void gxr_mp_gx_write_s8(s8 x);
void gxr_mp_gx_write_u16(u16 x);
void gxr_mp_gx_write_s16(s16 x);
void gxr_mp_gx_write_u32(u32 x);
void gxr_mp_gx_write_s32(s32 x);
void gxr_mp_gx_write_f32(float x);
void gxr_mp_gx_write_u64(u64 x);
void gxr_mp_gx_write_s64(s64 x);
void gxr_mp_gx_write_f64(double x);
void gxr_GXCallDisplayList(void*list,u32 nbytes);
void gxr_GXClearVtxDesc(void);
void gxr_GXSetVtxDesc(GXAttr a,GXAttrType t);
void gxr_GXSetVtxAttrFmt(GXVtxFmt f,GXAttr a,GXCompCnt c,GXCompType t,u8 frac);
void gxr_GXSetArray(GXAttr a,const void*p,u8 stride);
void gxr_GXSetCurrentMtx(u32 id);
void gxr_GXLoadPosMtxImm(Mtx m,u32 id);
void gxr_GXLoadNrmMtxImm(Mtx m,u32 id);
void gxr_GXLoadTexMtxImm(f32 m[][4],u32 id,GXTexMtxType type);
void gxr_GXSetProjection(Mtx44 m,GXProjectionType type);
void gxr_GXGetProjectionv(float*p);
void gxr_GXSetProjectionv(float*p);
void gxr_GXSetViewport(float x,float y,float w,float h,float n,float f);
void gxr_GXSetViewportJitter(float x,float y,float w,float h,float n,float f,u32 field);
void gxr_GXSetScissor(u32 x,u32 y,u32 w,u32 h);
void gxr_GXSetCullMode(GXCullMode mode);
void gxr_GXSetZMode(GXBool enable,GXCompare func,GXBool update);
void gxr_GXSetBlendMode(GXBlendMode type,GXBlendFactor src,GXBlendFactor dst,GXLogicOp op);
void gxr_GXSetChanMatColor(GXChannelID chan,GXColor c);
void gxr_GXSetChanAmbColor(GXChannelID chan,GXColor c);
void gxr_GXSetChanCtrl(GXChannelID chan,GXBool en,GXColorSrc a,GXColorSrc m,u32 mask,GXDiffuseFn diff,GXAttnFn attn);
void gxr_GXSetNumChans(u8 n);
void gxr_GXSetNumTexGens(u8 n);
void gxr_GXSetNumTevStages(u8 n);
void gxr_GXSetTexCoordGen2(GXTexCoordID id,GXTexGenType func,GXTexGenSrc src,u32 mtx,GXBool norm,u32 post);
void gxr_GXSetTevOrder(GXTevStageID s,GXTexCoordID coord,GXTexMapID map,GXChannelID color);
void gxr_GXSetTevColorIn(GXTevStageID s,GXTevColorArg a,GXTevColorArg b,GXTevColorArg c,GXTevColorArg d);
void gxr_GXSetTevAlphaIn(GXTevStageID s,GXTevAlphaArg a,GXTevAlphaArg b,GXTevAlphaArg c,GXTevAlphaArg d);
void gxr_GXSetTevColorOp(GXTevStageID s,GXTevOp op,GXTevBias bias,GXTevScale scale,GXBool clamp,GXTevRegID out);
void gxr_GXSetTevAlphaOp(GXTevStageID s,GXTevOp op,GXTevBias bias,GXTevScale scale,GXBool clamp,GXTevRegID out);
void gxr_GXSetTevSwapMode(GXTevStageID s,GXTevSwapSel ras,GXTevSwapSel tex);
void gxr_GXSetTevKColorSel(GXTevStageID s,GXTevKColorSel sel);
void gxr_GXSetTevKAlphaSel(GXTevStageID s,GXTevKAlphaSel sel);
void gxr_GXSetTevOp(GXTevStageID s,GXTevMode mode);
void gxr_GXSetTevColor(GXTevRegID id,GXColor c);
void gxr_GXSetTevKColor(GXTevKColorID id,GXColor c);
void gxr_GXSetColorUpdate(GXBool x);
void gxr_GXSetAlphaUpdate(GXBool x);
void gxr_GXSetDstAlpha(GXBool en,u8 a);
void gxr_GXSetDither(GXBool x);
void gxr_GXSetZCompLoc(GXBool x);
void gxr_GXSetAlphaCompare(GXCompare a,u8 refa,GXAlphaOp op,GXCompare b,u8 refb);
void gxr_GXPixModeSync(void);
void gxr_GXInitTexObj(GXTexObj*o,void*p,u16 w,u16 h,GXTexFmt fmt,GXTexWrapMode ws,GXTexWrapMode wt,u8 mip);
void gxr_GXInitTexObjCI(GXTexObj*o,void*p,u16 w,u16 h,GXTexFmt fmt,GXTexWrapMode ws,GXTexWrapMode wt,u8 mip,u32 tlut);
void gxr_GXInitTexObjLOD(GXTexObj*o,GXTexFilter min,GXTexFilter mag,f32 lo,f32 hi,f32 bias,GXBool clamp,GXBool edge,GXAnisotropy aniso);
void gxr_GXLoadTexObj(GXTexObj*o,GXTexMapID id);
void gxr_GXInitTlutObj(GXTlutObj*o,void*p,GXTlutFmt fmt,u16 n);
void gxr_GXLoadTlut(GXTlutObj*o,u32 id);
void gxr_GXInitLightColor(GXLightObj*o,GXColor c);
void gxr_GXInitLightDir(GXLightObj*o,float x,float y,float z);
void gxr_GXInitLightAttn(GXLightObj*o,float a,float b,float c,float d,float e,float f);
void gxr_GXLoadLightObjImm(GXLightObj*o,GXLightID id);
void gxr_GXInitLightPos(GXLightObj*o,float x,float y,float z);
void gxr_GXInitLightDistAttn(GXLightObj*o,float distance,float brightness,GXDistAttnFn kind);
void gxr_GXInitLightSpot(GXLightObj*o,float cutoff,GXSpotFn kind);
#endif
/* gx.c compiles every entry point as its replay implementation. */
#ifdef GX_FIFO_RENAME
#define mp_gx_source_write gxr_mp_gx_source_write
#define mp_gx_invalidate_sources gxr_mp_gx_invalidate_sources
#define mp_gx_configure_cache gxr_mp_gx_configure_cache
#define GXInit gxr_GXInit
#define GXSetMisc gxr_GXSetMisc
#define GXInvalidateVtxCache gxr_GXInvalidateVtxCache
#define GXInvalidateTexAll gxr_GXInvalidateTexAll
#define mp_gx_frame_texture_visibility gxr_mp_gx_frame_texture_visibility
#define GXSetTevClampMode gxr_GXSetTevClampMode
#define GXSetLineWidth gxr_GXSetLineWidth
#define GXSetPointSize gxr_GXSetPointSize
#define GXEnableTexOffsets gxr_GXEnableTexOffsets
#define GXGetTexBufferSize gxr_GXGetTexBufferSize
#define GXGetTexObjWidth gxr_GXGetTexObjWidth
#define GXGetTexObjHeight gxr_GXGetTexObjHeight
#define GXGetTexObjFmt gxr_GXGetTexObjFmt
#define GXGetViewportv gxr_GXGetViewportv
#define GXProject gxr_GXProject
#define GXSetTevColorS10 gxr_GXSetTevColorS10
#define GXSetTevSwapModeTable gxr_GXSetTevSwapModeTable
#define GXSetNumIndStages gxr_GXSetNumIndStages
#define GXSetTevDirect gxr_GXSetTevDirect
#define GXSetIndTexOrder gxr_GXSetIndTexOrder
#define GXSetIndTexCoordScale gxr_GXSetIndTexCoordScale
#define GXSetIndTexMtx gxr_GXSetIndTexMtx
#define GXSetTevIndirect gxr_GXSetTevIndirect
#define GXSetFog gxr_GXSetFog
#define GXInitFogAdjTable gxr_GXInitFogAdjTable
#define GXSetFogRangeAdj gxr_GXSetFogRangeAdj
#define GXSetPixelFmt gxr_GXSetPixelFmt
#define GXSetFieldMode gxr_GXSetFieldMode
#define GXSetZTexture gxr_GXSetZTexture
#define GXSetDispCopySrc gxr_GXSetDispCopySrc
#define GXSetDispCopyDst gxr_GXSetDispCopyDst
#define GXSetDispCopyYScale gxr_GXSetDispCopyYScale
#define GXSetCopyClear gxr_GXSetCopyClear
#define GXSetCopyClamp gxr_GXSetCopyClamp
#define GXSetDispCopyGamma gxr_GXSetDispCopyGamma
#define GXSetCopyFilter gxr_GXSetCopyFilter
#define GXSetTexCopySrc gxr_GXSetTexCopySrc
#define GXSetTexCopyDst gxr_GXSetTexCopyDst
#define GXCopyDisp gxr_GXCopyDisp
#define mp_gx_copy_mode gxr_mp_gx_copy_mode
#define GXSetDrawDoneCallback gxr_GXSetDrawDoneCallback
#define GXWaitDrawDone gxr_GXWaitDrawDone
#define GXSetDrawDone gxr_GXSetDrawDone
#define GXCopyTex gxr_GXCopyTex
#define mp_gx_copy_texture_only gxr_mp_gx_copy_texture_only
#define mp_gx_copy_clear_only gxr_mp_gx_copy_clear_only
#define GXDrawDone gxr_GXDrawDone
#define mp_gx_display_width gxr_mp_gx_display_width
#define mp_gx_camera_convergence gxr_mp_gx_camera_convergence
#define mp_gx_texture_mips gxr_mp_gx_texture_mips
#define mp_gx_left_capture gxr_mp_gx_left_capture
#define GXBegin gxr_GXBegin
#define mp_gx_write_u8 gxr_mp_gx_write_u8
#define mp_gx_write_s8 gxr_mp_gx_write_s8
#define mp_gx_write_u16 gxr_mp_gx_write_u16
#define mp_gx_write_s16 gxr_mp_gx_write_s16
#define mp_gx_write_u32 gxr_mp_gx_write_u32
#define mp_gx_write_s32 gxr_mp_gx_write_s32
#define mp_gx_write_f32 gxr_mp_gx_write_f32
#define mp_gx_write_u64 gxr_mp_gx_write_u64
#define mp_gx_write_s64 gxr_mp_gx_write_s64
#define mp_gx_write_f64 gxr_mp_gx_write_f64
#define GXCallDisplayList gxr_GXCallDisplayList
#define GXClearVtxDesc gxr_GXClearVtxDesc
#define GXSetVtxDesc gxr_GXSetVtxDesc
#define GXSetVtxAttrFmt gxr_GXSetVtxAttrFmt
#define GXSetArray gxr_GXSetArray
#define GXSetCurrentMtx gxr_GXSetCurrentMtx
#define GXLoadPosMtxImm gxr_GXLoadPosMtxImm
#define GXLoadNrmMtxImm gxr_GXLoadNrmMtxImm
#define GXLoadTexMtxImm gxr_GXLoadTexMtxImm
#define GXSetProjection gxr_GXSetProjection
#define GXGetProjectionv gxr_GXGetProjectionv
#define GXSetProjectionv gxr_GXSetProjectionv
#define GXSetViewport gxr_GXSetViewport
#define GXSetViewportJitter gxr_GXSetViewportJitter
#define GXSetScissor gxr_GXSetScissor
#define GXSetCullMode gxr_GXSetCullMode
#define GXSetZMode gxr_GXSetZMode
#define GXSetBlendMode gxr_GXSetBlendMode
#define GXSetChanMatColor gxr_GXSetChanMatColor
#define GXSetChanAmbColor gxr_GXSetChanAmbColor
#define GXSetChanCtrl gxr_GXSetChanCtrl
#define GXSetNumChans gxr_GXSetNumChans
#define GXSetNumTexGens gxr_GXSetNumTexGens
#define GXSetNumTevStages gxr_GXSetNumTevStages
#define GXSetTexCoordGen2 gxr_GXSetTexCoordGen2
#define GXSetTevOrder gxr_GXSetTevOrder
#define GXSetTevColorIn gxr_GXSetTevColorIn
#define GXSetTevAlphaIn gxr_GXSetTevAlphaIn
#define GXSetTevColorOp gxr_GXSetTevColorOp
#define GXSetTevAlphaOp gxr_GXSetTevAlphaOp
#define GXSetTevSwapMode gxr_GXSetTevSwapMode
#define GXSetTevKColorSel gxr_GXSetTevKColorSel
#define GXSetTevKAlphaSel gxr_GXSetTevKAlphaSel
#define GXSetTevOp gxr_GXSetTevOp
#define GXSetTevColor gxr_GXSetTevColor
#define GXSetTevKColor gxr_GXSetTevKColor
#define GXSetColorUpdate gxr_GXSetColorUpdate
#define GXSetAlphaUpdate gxr_GXSetAlphaUpdate
#define GXSetDstAlpha gxr_GXSetDstAlpha
#define GXSetDither gxr_GXSetDither
#define GXSetZCompLoc gxr_GXSetZCompLoc
#define GXSetAlphaCompare gxr_GXSetAlphaCompare
#define GXPixModeSync gxr_GXPixModeSync
#define GXInitTexObj gxr_GXInitTexObj
#define GXInitTexObjCI gxr_GXInitTexObjCI
#define GXInitTexObjLOD gxr_GXInitTexObjLOD
#define GXLoadTexObj gxr_GXLoadTexObj
#define GXInitTlutObj gxr_GXInitTlutObj
#define GXLoadTlut gxr_GXLoadTlut
#define GXInitLightColor gxr_GXInitLightColor
#define GXInitLightDir gxr_GXInitLightDir
#define GXInitLightAttn gxr_GXInitLightAttn
#define GXLoadLightObjImm gxr_GXLoadLightObjImm
#define GXInitLightPos gxr_GXInitLightPos
#define GXInitLightDistAttn gxr_GXInitLightDistAttn
#define GXInitLightSpot gxr_GXInitLightSpot
#endif
#ifdef GX_FIFO_RECORDERS
void mp_gx_source_write(const void*p,unsigned n){
    if(!mp_gx_async){gxr_mp_gx_source_write(p,n);return;}
    unsigned gx_words=3;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)p;gx_r[2]=(u32)n;
    gx_fifo_end(gx_r,GXOP_mp_gx_source_write,gx_words);
}
void mp_gx_invalidate_sources(void){
    if(!mp_gx_async){gxr_mp_gx_invalidate_sources();return;}
    unsigned gx_words=1;u32*gx_r=gx_fifo_begin(gx_words);
    
    gx_fifo_end(gx_r,GXOP_mp_gx_invalidate_sources,gx_words);
}
void mp_gx_configure_cache(unsigned bytes){gxr_mp_gx_configure_cache(bytes);}
void GXSetMisc(GXMiscToken t,u32 value){
    if(!mp_gx_async){gxr_GXSetMisc(t,value);return;}
    unsigned gx_words=3;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)t;gx_r[2]=(u32)value;
    gx_fifo_end(gx_r,GXOP_GXSetMisc,gx_words);
}
void GXInvalidateVtxCache(void){
    if(!mp_gx_async){gxr_GXInvalidateVtxCache();return;}
    unsigned gx_words=1;u32*gx_r=gx_fifo_begin(gx_words);
    
    gx_fifo_end(gx_r,GXOP_GXInvalidateVtxCache,gx_words);
}
void GXInvalidateTexAll(void){
    if(!mp_gx_async){gxr_GXInvalidateTexAll();return;}
    unsigned gx_words=1;u32*gx_r=gx_fifo_begin(gx_words);
    
    gx_fifo_end(gx_r,GXOP_GXInvalidateTexAll,gx_words);
}
void mp_gx_frame_texture_visibility(void){
    if(!mp_gx_async){gxr_mp_gx_frame_texture_visibility();return;}
    unsigned gx_words=1;u32*gx_r=gx_fifo_begin(gx_words);
    
    gx_fifo_end(gx_r,GXOP_mp_gx_frame_texture_visibility,gx_words);
}
void GXSetTevClampMode(int a,int b){
    if(!mp_gx_async){gxr_GXSetTevClampMode(a,b);return;}
    unsigned gx_words=3;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)a;gx_r[2]=(u32)b;
    gx_fifo_end(gx_r,GXOP_GXSetTevClampMode,gx_words);
}
void GXSetLineWidth(u8 w,GXTexOffset x){
    if(!mp_gx_async){gxr_GXSetLineWidth(w,x);return;}
    unsigned gx_words=3;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)w;gx_r[2]=(u32)x;
    gx_fifo_end(gx_r,GXOP_GXSetLineWidth,gx_words);
}
void GXSetPointSize(u8 w,GXTexOffset x){
    if(!mp_gx_async){gxr_GXSetPointSize(w,x);return;}
    unsigned gx_words=3;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)w;gx_r[2]=(u32)x;
    gx_fifo_end(gx_r,GXOP_GXSetPointSize,gx_words);
}
void GXEnableTexOffsets(GXTexCoordID id,u8 a,u8 b){
    if(!mp_gx_async){gxr_GXEnableTexOffsets(id,a,b);return;}
    unsigned gx_words=4;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)id;gx_r[2]=(u32)a;gx_r[3]=(u32)b;
    gx_fifo_end(gx_r,GXOP_GXEnableTexOffsets,gx_words);
}
u32 GXGetTexBufferSize(u16 w,u16 h,u32 fmt,u8 mip,u8 lod){return gxr_GXGetTexBufferSize(w,h,fmt,mip,lod);}
u16 GXGetTexObjWidth(const GXTexObj*o){return gxr_GXGetTexObjWidth(o);}
u16 GXGetTexObjHeight(const GXTexObj*o){return gxr_GXGetTexObjHeight(o);}
GXTexFmt GXGetTexObjFmt(const GXTexObj*o){return gxr_GXGetTexObjFmt(o);}
void GXProject(float x,float y,float z,float m[3][4],float*p,float*v,float*sx,float*sy,float*sz){gxr_GXProject(x,y,z,m,p,v,sx,sy,sz);}
void GXSetTevColorS10(GXTevRegID id,GXColorS10 c){
    if(!mp_gx_async){gxr_GXSetTevColorS10(id,c);return;}
    unsigned gx_words=4;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)id;memcpy(&gx_r[2],&c,8);
    gx_fifo_end(gx_r,GXOP_GXSetTevColorS10,gx_words);
}
void GXSetTevSwapModeTable(GXTevSwapSel id,GXTevColorChan r,GXTevColorChan g,GXTevColorChan b,GXTevColorChan a){
    if(!mp_gx_async){gxr_GXSetTevSwapModeTable(id,r,g,b,a);return;}
    unsigned gx_words=6;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)id;gx_r[2]=(u32)r;gx_r[3]=(u32)g;gx_r[4]=(u32)b;gx_r[5]=(u32)a;
    gx_fifo_end(gx_r,GXOP_GXSetTevSwapModeTable,gx_words);
}
void GXSetNumIndStages(u8 n){
    if(!mp_gx_async){gxr_GXSetNumIndStages(n);return;}
    unsigned gx_words=2;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)n;
    gx_fifo_end(gx_r,GXOP_GXSetNumIndStages,gx_words);
}
void GXSetTevDirect(GXTevStageID s){
    if(!mp_gx_async){gxr_GXSetTevDirect(s);return;}
    unsigned gx_words=2;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)s;
    gx_fifo_end(gx_r,GXOP_GXSetTevDirect,gx_words);
}
void GXSetIndTexOrder(GXIndTexStageID id,GXTexCoordID coord,GXTexMapID map){
    if(!mp_gx_async){gxr_GXSetIndTexOrder(id,coord,map);return;}
    unsigned gx_words=4;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)id;gx_r[2]=(u32)coord;gx_r[3]=(u32)map;
    gx_fifo_end(gx_r,GXOP_GXSetIndTexOrder,gx_words);
}
void GXSetIndTexCoordScale(GXIndTexStageID id,GXIndTexScale s,GXIndTexScale t){
    if(!mp_gx_async){gxr_GXSetIndTexCoordScale(id,s,t);return;}
    unsigned gx_words=4;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)id;gx_r[2]=(u32)s;gx_r[3]=(u32)t;
    gx_fifo_end(gx_r,GXOP_GXSetIndTexCoordScale,gx_words);
}
void GXSetIndTexMtx(GXIndTexMtxID id,float m[2][3],s8 e){
    if(!mp_gx_async){gxr_GXSetIndTexMtx(id,m,e);return;}
    unsigned gx_words=3+(6);u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)id;gx_r[2]=(u32)e;memcpy(&gx_r[3],m,(6)*4);
    gx_fifo_end(gx_r,GXOP_GXSetIndTexMtx,gx_words);
}
void GXSetTevIndirect(GXTevStageID s,GXIndTexStageID id,GXIndTexFormat f,GXIndTexBiasSel b,GXIndTexMtxID m,GXIndTexWrap ws,GXIndTexWrap wt,GXBool add,GXBool lod,GXIndTexAlphaSel a){
    if(!mp_gx_async){gxr_GXSetTevIndirect(s,id,f,b,m,ws,wt,add,lod,a);return;}
    unsigned gx_words=11;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)s;gx_r[2]=(u32)id;gx_r[3]=(u32)f;gx_r[4]=(u32)b;gx_r[5]=(u32)m;gx_r[6]=(u32)ws;gx_r[7]=(u32)wt;gx_r[8]=(u32)add;gx_r[9]=(u32)lod;gx_r[10]=(u32)a;
    gx_fifo_end(gx_r,GXOP_GXSetTevIndirect,gx_words);
}
void GXSetFog(GXFogType t,float s,float e,float n,float f,GXColor c){
    if(!mp_gx_async){gxr_GXSetFog(t,s,e,n,f,c);return;}
    unsigned gx_words=7;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)t;memcpy(&gx_r[2],&s,4);memcpy(&gx_r[3],&e,4);memcpy(&gx_r[4],&n,4);memcpy(&gx_r[5],&f,4);memcpy(&gx_r[6],&c,4);
    gx_fifo_end(gx_r,GXOP_GXSetFog,gx_words);
}
void GXInitFogAdjTable(GXFogAdjTable*t,u16 w,float p[4][4]){gxr_GXInitFogAdjTable(t,w,p);}
void GXSetFogRangeAdj(GXBool b,u16 c,GXFogAdjTable*t){
    if(!mp_gx_async){gxr_GXSetFogRangeAdj(b,c,t);return;}
    unsigned gx_words=3+1+(((sizeof(GXFogAdjTable))+3)/4);u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)b;gx_r[2]=(u32)c;gx_r[3]=t!=0;if(t)memcpy(&gx_r[3+1],t,sizeof(GXFogAdjTable));
    gx_fifo_end(gx_r,GXOP_GXSetFogRangeAdj,gx_words);
}
void GXSetPixelFmt(GXPixelFmt p,GXZFmt16 z){
    if(!mp_gx_async){gxr_GXSetPixelFmt(p,z);return;}
    unsigned gx_words=3;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)p;gx_r[2]=(u32)z;
    gx_fifo_end(gx_r,GXOP_GXSetPixelFmt,gx_words);
}
void GXSetFieldMode(GXBool f,GXBool a){
    if(!mp_gx_async){gxr_GXSetFieldMode(f,a);return;}
    unsigned gx_words=3;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)f;gx_r[2]=(u32)a;
    gx_fifo_end(gx_r,GXOP_GXSetFieldMode,gx_words);
}
void GXSetZTexture(GXZTexOp o,GXTexFmt f,u32 b){
    if(!mp_gx_async){gxr_GXSetZTexture(o,f,b);return;}
    unsigned gx_words=4;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)o;gx_r[2]=(u32)f;gx_r[3]=(u32)b;
    gx_fifo_end(gx_r,GXOP_GXSetZTexture,gx_words);
}
void GXSetDispCopySrc(u16 x,u16 y,u16 w,u16 h){gx_mirror_GXSetDispCopySrc(x,y,w,h);
    if(!mp_gx_async){gxr_GXSetDispCopySrc(x,y,w,h);return;}
    unsigned gx_words=5;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)x;gx_r[2]=(u32)y;gx_r[3]=(u32)w;gx_r[4]=(u32)h;
    gx_fifo_end(gx_r,GXOP_GXSetDispCopySrc,gx_words);
}
void GXSetDispCopyDst(u16 w,u16 h){
    if(!mp_gx_async){gxr_GXSetDispCopyDst(w,h);return;}
    unsigned gx_words=3;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)w;gx_r[2]=(u32)h;
    gx_fifo_end(gx_r,GXOP_GXSetDispCopyDst,gx_words);
}
void GXSetCopyClear(GXColor c,u32 z){
    if(!mp_gx_async){gxr_GXSetCopyClear(c,z);return;}
    unsigned gx_words=3;u32*gx_r=gx_fifo_begin(gx_words);
    memcpy(&gx_r[1],&c,4);gx_r[2]=(u32)z;
    gx_fifo_end(gx_r,GXOP_GXSetCopyClear,gx_words);
}
void GXSetCopyClamp(GXFBClamp c){
    if(!mp_gx_async){gxr_GXSetCopyClamp(c);return;}
    unsigned gx_words=2;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)c;
    gx_fifo_end(gx_r,GXOP_GXSetCopyClamp,gx_words);
}
void GXSetDispCopyGamma(GXGamma g){
    if(!mp_gx_async){gxr_GXSetDispCopyGamma(g);return;}
    unsigned gx_words=2;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)g;
    gx_fifo_end(gx_r,GXOP_GXSetDispCopyGamma,gx_words);
}
void GXSetCopyFilter(GXBool aa,const u8 p[12][2],GXBool vf,const u8 f[7]){
    if(!mp_gx_async){gxr_GXSetCopyFilter(aa,p,vf,f);return;}
    unsigned gx_words=3+1+(((24)+3)/4)+1+(((7)+3)/4);u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)aa;gx_r[2]=(u32)vf;gx_r[3]=p!=0;if(p)memcpy(&gx_r[3+1],p,24);gx_r[3+1+(((24)+3)/4)]=f!=0;if(f)memcpy(&gx_r[3+1+(((24)+3)/4)+1],f,7);
    gx_fifo_end(gx_r,GXOP_GXSetCopyFilter,gx_words);
}
void GXSetTexCopySrc(u16 x,u16 y,u16 w,u16 h){
    if(!mp_gx_async){gxr_GXSetTexCopySrc(x,y,w,h);return;}
    unsigned gx_words=5;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)x;gx_r[2]=(u32)y;gx_r[3]=(u32)w;gx_r[4]=(u32)h;
    gx_fifo_end(gx_r,GXOP_GXSetTexCopySrc,gx_words);
}
void GXSetTexCopyDst(u16 w,u16 h,GXTexFmt fmt,GXBool mip){
    if(!mp_gx_async){gxr_GXSetTexCopyDst(w,h,fmt,mip);return;}
    unsigned gx_words=5;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)w;gx_r[2]=(u32)h;gx_r[3]=(u32)fmt;gx_r[4]=(u32)mip;
    gx_fifo_end(gx_r,GXOP_GXSetTexCopyDst,gx_words);
}
void GXCopyDisp(void*dest,GXBool clear){
    if(!mp_gx_async){gxr_GXCopyDisp(dest,clear);return;}
    unsigned gx_words=3;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)dest;gx_r[2]=(u32)clear;
    gx_fifo_end(gx_r,GXOP_GXCopyDisp,gx_words);
}
void mp_gx_copy_mode(u32 mode){
    if(!mp_gx_async){gxr_mp_gx_copy_mode(mode);return;}
    unsigned gx_words=2;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)mode;
    gx_fifo_end(gx_r,GXOP_mp_gx_copy_mode,gx_words);
}
void GXCopyTex(void*dest,GXBool clear){
    if(!mp_gx_async){gxr_GXCopyTex(dest,clear);return;}
    unsigned gx_words=3;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)dest;gx_r[2]=(u32)clear;
    gx_fifo_end(gx_r,GXOP_GXCopyTex,gx_words);
}
void mp_gx_copy_texture_only(void*dest,int clear){
    if(!mp_gx_async){gxr_mp_gx_copy_texture_only(dest,clear);return;}
    unsigned gx_words=3;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)dest;gx_r[2]=(u32)clear;
    gx_fifo_end(gx_r,GXOP_mp_gx_copy_texture_only,gx_words);
}
void mp_gx_copy_clear_only(void*dest,int clear){
    if(!mp_gx_async){gxr_mp_gx_copy_clear_only(dest,clear);return;}
    unsigned gx_words=3;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)dest;gx_r[2]=(u32)clear;
    gx_fifo_end(gx_r,GXOP_mp_gx_copy_clear_only,gx_words);
}
void mp_gx_display_width(unsigned width){
    if(!mp_gx_async){gxr_mp_gx_display_width(width);return;}
    unsigned gx_words=2;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)width;
    gx_fifo_end(gx_r,GXOP_mp_gx_display_width,gx_words);
}
void mp_gx_camera_convergence(float convergence){
    if(!mp_gx_async){gxr_mp_gx_camera_convergence(convergence);return;}
    unsigned gx_words=2;u32*gx_r=gx_fifo_begin(gx_words);
    memcpy(&gx_r[1],&convergence,4);
    gx_fifo_end(gx_r,GXOP_mp_gx_camera_convergence,gx_words);
}
void mp_gx_texture_mips(unsigned enable){
    if(!mp_gx_async){gxr_mp_gx_texture_mips(enable);return;}
    unsigned gx_words=2;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)enable;
    gx_fifo_end(gx_r,GXOP_mp_gx_texture_mips,gx_words);
}
void GXBegin(GXPrimitive type,GXVtxFmt fmt,u16 nverts){
    if(!mp_gx_async){gxr_GXBegin(type,fmt,nverts);return;}
    unsigned gx_words=4;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)type;gx_r[2]=(u32)fmt;gx_r[3]=(u32)nverts;
    gx_fifo_end(gx_r,GXOP_GXBegin,gx_words);
}
void GXClearVtxDesc(void){
    if(!mp_gx_async){gxr_GXClearVtxDesc();return;}
    unsigned gx_words=1;u32*gx_r=gx_fifo_begin(gx_words);
    
    gx_fifo_end(gx_r,GXOP_GXClearVtxDesc,gx_words);
}
void GXSetVtxDesc(GXAttr a,GXAttrType t){
    if(!mp_gx_async){gxr_GXSetVtxDesc(a,t);return;}
    unsigned gx_words=3;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)a;gx_r[2]=(u32)t;
    gx_fifo_end(gx_r,GXOP_GXSetVtxDesc,gx_words);
}
void GXSetVtxAttrFmt(GXVtxFmt f,GXAttr a,GXCompCnt c,GXCompType t,u8 frac){
    if(!mp_gx_async){gxr_GXSetVtxAttrFmt(f,a,c,t,frac);return;}
    unsigned gx_words=6;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)f;gx_r[2]=(u32)a;gx_r[3]=(u32)c;gx_r[4]=(u32)t;gx_r[5]=(u32)frac;
    gx_fifo_end(gx_r,GXOP_GXSetVtxAttrFmt,gx_words);
}
void GXSetArray(GXAttr a,const void*p,u8 stride){
    if(!mp_gx_async){gxr_GXSetArray(a,p,stride);return;}
    unsigned gx_words=4;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)a;gx_r[2]=(u32)p;gx_r[3]=(u32)stride;
    gx_fifo_end(gx_r,GXOP_GXSetArray,gx_words);
}
void GXSetCurrentMtx(u32 id){
    if(!mp_gx_async){gxr_GXSetCurrentMtx(id);return;}
    unsigned gx_words=2;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)id;
    gx_fifo_end(gx_r,GXOP_GXSetCurrentMtx,gx_words);
}
void GXLoadPosMtxImm(Mtx m,u32 id){
    if(!mp_gx_async){gxr_GXLoadPosMtxImm(m,id);return;}
    unsigned gx_words=2+(12);u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)id;memcpy(&gx_r[2],m,(12)*4);
    gx_fifo_end(gx_r,GXOP_GXLoadPosMtxImm,gx_words);
}
void GXLoadNrmMtxImm(Mtx m,u32 id){
    if(!mp_gx_async){gxr_GXLoadNrmMtxImm(m,id);return;}
    unsigned gx_words=2+(12);u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)id;memcpy(&gx_r[2],m,(12)*4);
    gx_fifo_end(gx_r,GXOP_GXLoadNrmMtxImm,gx_words);
}
void GXLoadTexMtxImm(f32 m[][4],u32 id,GXTexMtxType type){
    if(!mp_gx_async){gxr_GXLoadTexMtxImm(m,id,type);return;}
    unsigned gx_words=3+(type==GX_MTX2x4?8:12);u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)id;gx_r[2]=(u32)type;memcpy(&gx_r[3],m,(type==GX_MTX2x4?8:12)*4);
    gx_fifo_end(gx_r,GXOP_GXLoadTexMtxImm,gx_words);
}
void GXSetProjection(Mtx44 m,GXProjectionType type){gx_mirror_GXSetProjection(m,type);
    if(!mp_gx_async){gxr_GXSetProjection(m,type);return;}
    unsigned gx_words=2+(16);u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)type;memcpy(&gx_r[2],m,(16)*4);
    gx_fifo_end(gx_r,GXOP_GXSetProjection,gx_words);
}
void GXSetProjectionv(float*p){gx_mirror_GXSetProjectionv(p);
    if(!mp_gx_async){gxr_GXSetProjectionv(p);return;}
    unsigned gx_words=1+(7);u32*gx_r=gx_fifo_begin(gx_words);
    memcpy(&gx_r[1],p,(7)*4);
    gx_fifo_end(gx_r,GXOP_GXSetProjectionv,gx_words);
}
void GXSetViewport(float x,float y,float w,float h,float n,float f){gx_mirror_GXSetViewport(x,y,w,h,n,f);
    if(!mp_gx_async){gxr_GXSetViewport(x,y,w,h,n,f);return;}
    unsigned gx_words=7;u32*gx_r=gx_fifo_begin(gx_words);
    memcpy(&gx_r[1],&x,4);memcpy(&gx_r[2],&y,4);memcpy(&gx_r[3],&w,4);memcpy(&gx_r[4],&h,4);memcpy(&gx_r[5],&n,4);memcpy(&gx_r[6],&f,4);
    gx_fifo_end(gx_r,GXOP_GXSetViewport,gx_words);
}
void GXSetViewportJitter(float x,float y,float w,float h,float n,float f,u32 field){gx_mirror_GXSetViewportJitter(x,y,w,h,n,f,field);
    if(!mp_gx_async){gxr_GXSetViewportJitter(x,y,w,h,n,f,field);return;}
    unsigned gx_words=8;u32*gx_r=gx_fifo_begin(gx_words);
    memcpy(&gx_r[1],&x,4);memcpy(&gx_r[2],&y,4);memcpy(&gx_r[3],&w,4);memcpy(&gx_r[4],&h,4);memcpy(&gx_r[5],&n,4);memcpy(&gx_r[6],&f,4);gx_r[7]=(u32)field;
    gx_fifo_end(gx_r,GXOP_GXSetViewportJitter,gx_words);
}
void GXSetScissor(u32 x,u32 y,u32 w,u32 h){
    if(!mp_gx_async){gxr_GXSetScissor(x,y,w,h);return;}
    unsigned gx_words=5;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)x;gx_r[2]=(u32)y;gx_r[3]=(u32)w;gx_r[4]=(u32)h;
    gx_fifo_end(gx_r,GXOP_GXSetScissor,gx_words);
}
void GXSetCullMode(GXCullMode mode){
    if(!mp_gx_async){gxr_GXSetCullMode(mode);return;}
    unsigned gx_words=2;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)mode;
    gx_fifo_end(gx_r,GXOP_GXSetCullMode,gx_words);
}
void GXSetZMode(GXBool enable,GXCompare func,GXBool update){
    if(!mp_gx_async){gxr_GXSetZMode(enable,func,update);return;}
    unsigned gx_words=4;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)enable;gx_r[2]=(u32)func;gx_r[3]=(u32)update;
    gx_fifo_end(gx_r,GXOP_GXSetZMode,gx_words);
}
void GXSetBlendMode(GXBlendMode type,GXBlendFactor src,GXBlendFactor dst,GXLogicOp op){
    if(!mp_gx_async){gxr_GXSetBlendMode(type,src,dst,op);return;}
    unsigned gx_words=5;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)type;gx_r[2]=(u32)src;gx_r[3]=(u32)dst;gx_r[4]=(u32)op;
    gx_fifo_end(gx_r,GXOP_GXSetBlendMode,gx_words);
}
void GXSetChanMatColor(GXChannelID chan,GXColor c){
    if(!mp_gx_async){gxr_GXSetChanMatColor(chan,c);return;}
    unsigned gx_words=3;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)chan;memcpy(&gx_r[2],&c,4);
    gx_fifo_end(gx_r,GXOP_GXSetChanMatColor,gx_words);
}
void GXSetChanAmbColor(GXChannelID chan,GXColor c){
    if(!mp_gx_async){gxr_GXSetChanAmbColor(chan,c);return;}
    unsigned gx_words=3;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)chan;memcpy(&gx_r[2],&c,4);
    gx_fifo_end(gx_r,GXOP_GXSetChanAmbColor,gx_words);
}
void GXSetChanCtrl(GXChannelID chan,GXBool en,GXColorSrc a,GXColorSrc m,u32 mask,GXDiffuseFn diff,GXAttnFn attn){
    if(!mp_gx_async){gxr_GXSetChanCtrl(chan,en,a,m,mask,diff,attn);return;}
    unsigned gx_words=8;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)chan;gx_r[2]=(u32)en;gx_r[3]=(u32)a;gx_r[4]=(u32)m;gx_r[5]=(u32)mask;gx_r[6]=(u32)diff;gx_r[7]=(u32)attn;
    gx_fifo_end(gx_r,GXOP_GXSetChanCtrl,gx_words);
}
void GXSetNumChans(u8 n){
    if(!mp_gx_async){gxr_GXSetNumChans(n);return;}
    unsigned gx_words=2;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)n;
    gx_fifo_end(gx_r,GXOP_GXSetNumChans,gx_words);
}
void GXSetNumTexGens(u8 n){
    if(!mp_gx_async){gxr_GXSetNumTexGens(n);return;}
    unsigned gx_words=2;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)n;
    gx_fifo_end(gx_r,GXOP_GXSetNumTexGens,gx_words);
}
void GXSetNumTevStages(u8 n){
    if(!mp_gx_async){gxr_GXSetNumTevStages(n);return;}
    unsigned gx_words=2;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)n;
    gx_fifo_end(gx_r,GXOP_GXSetNumTevStages,gx_words);
}
void GXSetTexCoordGen2(GXTexCoordID id,GXTexGenType func,GXTexGenSrc src,u32 mtx,GXBool norm,u32 post){
    if(!mp_gx_async){gxr_GXSetTexCoordGen2(id,func,src,mtx,norm,post);return;}
    unsigned gx_words=7;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)id;gx_r[2]=(u32)func;gx_r[3]=(u32)src;gx_r[4]=(u32)mtx;gx_r[5]=(u32)norm;gx_r[6]=(u32)post;
    gx_fifo_end(gx_r,GXOP_GXSetTexCoordGen2,gx_words);
}
void GXSetTevOrder(GXTevStageID s,GXTexCoordID coord,GXTexMapID map,GXChannelID color){
    if(!mp_gx_async){gxr_GXSetTevOrder(s,coord,map,color);return;}
    unsigned gx_words=5;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)s;gx_r[2]=(u32)coord;gx_r[3]=(u32)map;gx_r[4]=(u32)color;
    gx_fifo_end(gx_r,GXOP_GXSetTevOrder,gx_words);
}
void GXSetTevColorIn(GXTevStageID s,GXTevColorArg a,GXTevColorArg b,GXTevColorArg c,GXTevColorArg d){
    if(!mp_gx_async){gxr_GXSetTevColorIn(s,a,b,c,d);return;}
    unsigned gx_words=6;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)s;gx_r[2]=(u32)a;gx_r[3]=(u32)b;gx_r[4]=(u32)c;gx_r[5]=(u32)d;
    gx_fifo_end(gx_r,GXOP_GXSetTevColorIn,gx_words);
}
void GXSetTevAlphaIn(GXTevStageID s,GXTevAlphaArg a,GXTevAlphaArg b,GXTevAlphaArg c,GXTevAlphaArg d){
    if(!mp_gx_async){gxr_GXSetTevAlphaIn(s,a,b,c,d);return;}
    unsigned gx_words=6;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)s;gx_r[2]=(u32)a;gx_r[3]=(u32)b;gx_r[4]=(u32)c;gx_r[5]=(u32)d;
    gx_fifo_end(gx_r,GXOP_GXSetTevAlphaIn,gx_words);
}
void GXSetTevColorOp(GXTevStageID s,GXTevOp op,GXTevBias bias,GXTevScale scale,GXBool clamp,GXTevRegID out){
    if(!mp_gx_async){gxr_GXSetTevColorOp(s,op,bias,scale,clamp,out);return;}
    unsigned gx_words=7;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)s;gx_r[2]=(u32)op;gx_r[3]=(u32)bias;gx_r[4]=(u32)scale;gx_r[5]=(u32)clamp;gx_r[6]=(u32)out;
    gx_fifo_end(gx_r,GXOP_GXSetTevColorOp,gx_words);
}
void GXSetTevAlphaOp(GXTevStageID s,GXTevOp op,GXTevBias bias,GXTevScale scale,GXBool clamp,GXTevRegID out){
    if(!mp_gx_async){gxr_GXSetTevAlphaOp(s,op,bias,scale,clamp,out);return;}
    unsigned gx_words=7;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)s;gx_r[2]=(u32)op;gx_r[3]=(u32)bias;gx_r[4]=(u32)scale;gx_r[5]=(u32)clamp;gx_r[6]=(u32)out;
    gx_fifo_end(gx_r,GXOP_GXSetTevAlphaOp,gx_words);
}
void GXSetTevSwapMode(GXTevStageID s,GXTevSwapSel ras,GXTevSwapSel tex){
    if(!mp_gx_async){gxr_GXSetTevSwapMode(s,ras,tex);return;}
    unsigned gx_words=4;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)s;gx_r[2]=(u32)ras;gx_r[3]=(u32)tex;
    gx_fifo_end(gx_r,GXOP_GXSetTevSwapMode,gx_words);
}
void GXSetTevKColorSel(GXTevStageID s,GXTevKColorSel sel){
    if(!mp_gx_async){gxr_GXSetTevKColorSel(s,sel);return;}
    unsigned gx_words=3;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)s;gx_r[2]=(u32)sel;
    gx_fifo_end(gx_r,GXOP_GXSetTevKColorSel,gx_words);
}
void GXSetTevKAlphaSel(GXTevStageID s,GXTevKAlphaSel sel){
    if(!mp_gx_async){gxr_GXSetTevKAlphaSel(s,sel);return;}
    unsigned gx_words=3;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)s;gx_r[2]=(u32)sel;
    gx_fifo_end(gx_r,GXOP_GXSetTevKAlphaSel,gx_words);
}
void GXSetTevOp(GXTevStageID s,GXTevMode mode){
    if(!mp_gx_async){gxr_GXSetTevOp(s,mode);return;}
    unsigned gx_words=3;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)s;gx_r[2]=(u32)mode;
    gx_fifo_end(gx_r,GXOP_GXSetTevOp,gx_words);
}
void GXSetTevColor(GXTevRegID id,GXColor c){
    if(!mp_gx_async){gxr_GXSetTevColor(id,c);return;}
    unsigned gx_words=3;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)id;memcpy(&gx_r[2],&c,4);
    gx_fifo_end(gx_r,GXOP_GXSetTevColor,gx_words);
}
void GXSetTevKColor(GXTevKColorID id,GXColor c){
    if(!mp_gx_async){gxr_GXSetTevKColor(id,c);return;}
    unsigned gx_words=3;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)id;memcpy(&gx_r[2],&c,4);
    gx_fifo_end(gx_r,GXOP_GXSetTevKColor,gx_words);
}
void GXSetColorUpdate(GXBool x){
    if(!mp_gx_async){gxr_GXSetColorUpdate(x);return;}
    unsigned gx_words=2;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)x;
    gx_fifo_end(gx_r,GXOP_GXSetColorUpdate,gx_words);
}
void GXSetAlphaUpdate(GXBool x){
    if(!mp_gx_async){gxr_GXSetAlphaUpdate(x);return;}
    unsigned gx_words=2;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)x;
    gx_fifo_end(gx_r,GXOP_GXSetAlphaUpdate,gx_words);
}
void GXSetDstAlpha(GXBool en,u8 a){
    if(!mp_gx_async){gxr_GXSetDstAlpha(en,a);return;}
    unsigned gx_words=3;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)en;gx_r[2]=(u32)a;
    gx_fifo_end(gx_r,GXOP_GXSetDstAlpha,gx_words);
}
void GXSetDither(GXBool x){
    if(!mp_gx_async){gxr_GXSetDither(x);return;}
    unsigned gx_words=2;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)x;
    gx_fifo_end(gx_r,GXOP_GXSetDither,gx_words);
}
void GXSetZCompLoc(GXBool x){
    if(!mp_gx_async){gxr_GXSetZCompLoc(x);return;}
    unsigned gx_words=2;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)x;
    gx_fifo_end(gx_r,GXOP_GXSetZCompLoc,gx_words);
}
void GXSetAlphaCompare(GXCompare a,u8 refa,GXAlphaOp op,GXCompare b,u8 refb){
    if(!mp_gx_async){gxr_GXSetAlphaCompare(a,refa,op,b,refb);return;}
    unsigned gx_words=6;u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)a;gx_r[2]=(u32)refa;gx_r[3]=(u32)op;gx_r[4]=(u32)b;gx_r[5]=(u32)refb;
    gx_fifo_end(gx_r,GXOP_GXSetAlphaCompare,gx_words);
}
void GXPixModeSync(void){
    if(!mp_gx_async){gxr_GXPixModeSync();return;}
    unsigned gx_words=1;u32*gx_r=gx_fifo_begin(gx_words);
    
    gx_fifo_end(gx_r,GXOP_GXPixModeSync,gx_words);
}
void GXInitTexObj(GXTexObj*o,void*p,u16 w,u16 h,GXTexFmt fmt,GXTexWrapMode ws,GXTexWrapMode wt,u8 mip){gxr_GXInitTexObj(o,p,w,h,fmt,ws,wt,mip);}
void GXInitTexObjCI(GXTexObj*o,void*p,u16 w,u16 h,GXTexFmt fmt,GXTexWrapMode ws,GXTexWrapMode wt,u8 mip,u32 tlut){gxr_GXInitTexObjCI(o,p,w,h,fmt,ws,wt,mip,tlut);}
void GXInitTexObjLOD(GXTexObj*o,GXTexFilter min,GXTexFilter mag,f32 lo,f32 hi,f32 bias,GXBool clamp,GXBool edge,GXAnisotropy aniso){gxr_GXInitTexObjLOD(o,min,mag,lo,hi,bias,clamp,edge,aniso);}
void GXLoadTexObj(GXTexObj*o,GXTexMapID id){
    if(!mp_gx_async){gxr_GXLoadTexObj(o,id);return;}
    unsigned gx_words=2+(sizeof(GXTexObj)/4);u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)id;memcpy(&gx_r[2],o,(sizeof(GXTexObj)/4)*4);
    gx_fifo_end(gx_r,GXOP_GXLoadTexObj,gx_words);
}
void GXInitTlutObj(GXTlutObj*o,void*p,GXTlutFmt fmt,u16 n){gxr_GXInitTlutObj(o,p,fmt,n);}
void GXLoadTlut(GXTlutObj*o,u32 id){
    if(!mp_gx_async){gxr_GXLoadTlut(o,id);return;}
    unsigned gx_words=2+(sizeof(GXTlutObj)/4);u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)id;memcpy(&gx_r[2],o,(sizeof(GXTlutObj)/4)*4);
    gx_fifo_end(gx_r,GXOP_GXLoadTlut,gx_words);
}
void GXInitLightColor(GXLightObj*o,GXColor c){gxr_GXInitLightColor(o,c);}
void GXInitLightDir(GXLightObj*o,float x,float y,float z){gxr_GXInitLightDir(o,x,y,z);}
void GXInitLightAttn(GXLightObj*o,float a,float b,float c,float d,float e,float f){gxr_GXInitLightAttn(o,a,b,c,d,e,f);}
void GXLoadLightObjImm(GXLightObj*o,GXLightID id){
    if(!mp_gx_async){gxr_GXLoadLightObjImm(o,id);return;}
    unsigned gx_words=2+(sizeof(GXLightObj)/4);u32*gx_r=gx_fifo_begin(gx_words);
    gx_r[1]=(u32)id;memcpy(&gx_r[2],o,(sizeof(GXLightObj)/4)*4);
    gx_fifo_end(gx_r,GXOP_GXLoadLightObjImm,gx_words);
}
void GXInitLightPos(GXLightObj*o,float x,float y,float z){gxr_GXInitLightPos(o,x,y,z);}
void GXInitLightDistAttn(GXLightObj*o,float distance,float brightness,GXDistAttnFn kind){gxr_GXInitLightDistAttn(o,distance,brightness,kind);}
void GXInitLightSpot(GXLightObj*o,float cutoff,GXSpotFn kind){gxr_GXInitLightSpot(o,cutoff,kind);}
static void gx_replay_generated(unsigned op,const u32*r){
    switch(op){
    case GXOP_mp_gx_source_write:gxr_mp_gx_source_write((const void*)r[1],(unsigned)r[2]);break;
    case GXOP_mp_gx_invalidate_sources:gxr_mp_gx_invalidate_sources();break;
    case GXOP_GXSetMisc:gxr_GXSetMisc((GXMiscToken)r[1],(u32)r[2]);break;
    case GXOP_GXInvalidateVtxCache:gxr_GXInvalidateVtxCache();break;
    case GXOP_GXInvalidateTexAll:gxr_GXInvalidateTexAll();break;
    case GXOP_mp_gx_frame_texture_visibility:gxr_mp_gx_frame_texture_visibility();break;
    case GXOP_GXSetTevClampMode:gxr_GXSetTevClampMode((int)r[1],(int)r[2]);break;
    case GXOP_GXSetLineWidth:gxr_GXSetLineWidth((u8)r[1],(GXTexOffset)r[2]);break;
    case GXOP_GXSetPointSize:gxr_GXSetPointSize((u8)r[1],(GXTexOffset)r[2]);break;
    case GXOP_GXEnableTexOffsets:gxr_GXEnableTexOffsets((GXTexCoordID)r[1],(u8)r[2],(u8)r[3]);break;
    case GXOP_GXSetTevColorS10:gxr_GXSetTevColorS10((GXTevRegID)r[1],gx_fifo_color_s10(&r[2]));break;
    case GXOP_GXSetTevSwapModeTable:gxr_GXSetTevSwapModeTable((GXTevSwapSel)r[1],(GXTevColorChan)r[2],(GXTevColorChan)r[3],(GXTevColorChan)r[4],(GXTevColorChan)r[5]);break;
    case GXOP_GXSetNumIndStages:gxr_GXSetNumIndStages((u8)r[1]);break;
    case GXOP_GXSetTevDirect:gxr_GXSetTevDirect((GXTevStageID)r[1]);break;
    case GXOP_GXSetIndTexOrder:gxr_GXSetIndTexOrder((GXIndTexStageID)r[1],(GXTexCoordID)r[2],(GXTexMapID)r[3]);break;
    case GXOP_GXSetIndTexCoordScale:gxr_GXSetIndTexCoordScale((GXIndTexStageID)r[1],(GXIndTexScale)r[2],(GXIndTexScale)r[3]);break;
    case GXOP_GXSetIndTexMtx:gxr_GXSetIndTexMtx((GXIndTexMtxID)r[1],(void*)&r[3],(s8)r[2]);break;
    case GXOP_GXSetTevIndirect:gxr_GXSetTevIndirect((GXTevStageID)r[1],(GXIndTexStageID)r[2],(GXIndTexFormat)r[3],(GXIndTexBiasSel)r[4],(GXIndTexMtxID)r[5],(GXIndTexWrap)r[6],(GXIndTexWrap)r[7],(GXBool)r[8],(GXBool)r[9],(GXIndTexAlphaSel)r[10]);break;
    case GXOP_GXSetFog:gxr_GXSetFog((GXFogType)r[1],gx_fifo_float(r[2]),gx_fifo_float(r[3]),gx_fifo_float(r[4]),gx_fifo_float(r[5]),gx_fifo_color(r[6]));break;
    case GXOP_GXSetFogRangeAdj:gxr_GXSetFogRangeAdj((GXBool)r[1],(u16)r[2],(r[3]?(void*)&r[3+1]:(void*)0));break;
    case GXOP_GXSetPixelFmt:gxr_GXSetPixelFmt((GXPixelFmt)r[1],(GXZFmt16)r[2]);break;
    case GXOP_GXSetFieldMode:gxr_GXSetFieldMode((GXBool)r[1],(GXBool)r[2]);break;
    case GXOP_GXSetZTexture:gxr_GXSetZTexture((GXZTexOp)r[1],(GXTexFmt)r[2],(u32)r[3]);break;
    case GXOP_GXSetDispCopySrc:gxr_GXSetDispCopySrc((u16)r[1],(u16)r[2],(u16)r[3],(u16)r[4]);break;
    case GXOP_GXSetDispCopyDst:gxr_GXSetDispCopyDst((u16)r[1],(u16)r[2]);break;
    case GXOP_GXSetCopyClear:gxr_GXSetCopyClear(gx_fifo_color(r[1]),(u32)r[2]);break;
    case GXOP_GXSetCopyClamp:gxr_GXSetCopyClamp((GXFBClamp)r[1]);break;
    case GXOP_GXSetDispCopyGamma:gxr_GXSetDispCopyGamma((GXGamma)r[1]);break;
    case GXOP_GXSetCopyFilter:gxr_GXSetCopyFilter((GXBool)r[1],(r[3]?(void*)&r[3+1]:(void*)0),(GXBool)r[2],(r[3+1+(((24)+3)/4)]?(void*)&r[3+1+(((24)+3)/4)+1]:(void*)0));break;
    case GXOP_GXSetTexCopySrc:gxr_GXSetTexCopySrc((u16)r[1],(u16)r[2],(u16)r[3],(u16)r[4]);break;
    case GXOP_GXSetTexCopyDst:gxr_GXSetTexCopyDst((u16)r[1],(u16)r[2],(GXTexFmt)r[3],(GXBool)r[4]);break;
    case GXOP_GXCopyDisp:gxr_GXCopyDisp((void*)r[1],(GXBool)r[2]);break;
    case GXOP_mp_gx_copy_mode:gxr_mp_gx_copy_mode((u32)r[1]);break;
    case GXOP_GXCopyTex:gxr_GXCopyTex((void*)r[1],(GXBool)r[2]);break;
    case GXOP_mp_gx_copy_texture_only:gxr_mp_gx_copy_texture_only((void*)r[1],(int)r[2]);break;
    case GXOP_mp_gx_copy_clear_only:gxr_mp_gx_copy_clear_only((void*)r[1],(int)r[2]);break;
    case GXOP_mp_gx_display_width:gxr_mp_gx_display_width((unsigned)r[1]);break;
    case GXOP_mp_gx_camera_convergence:gxr_mp_gx_camera_convergence(gx_fifo_float(r[1]));break;
    case GXOP_mp_gx_texture_mips:gxr_mp_gx_texture_mips((unsigned)r[1]);break;
    case GXOP_GXBegin:gxr_GXBegin((GXPrimitive)r[1],(GXVtxFmt)r[2],(u16)r[3]);break;
    case GXOP_GXClearVtxDesc:gxr_GXClearVtxDesc();break;
    case GXOP_GXSetVtxDesc:gxr_GXSetVtxDesc((GXAttr)r[1],(GXAttrType)r[2]);break;
    case GXOP_GXSetVtxAttrFmt:gxr_GXSetVtxAttrFmt((GXVtxFmt)r[1],(GXAttr)r[2],(GXCompCnt)r[3],(GXCompType)r[4],(u8)r[5]);break;
    case GXOP_GXSetArray:gxr_GXSetArray((GXAttr)r[1],(const void*)r[2],(u8)r[3]);break;
    case GXOP_GXSetCurrentMtx:gxr_GXSetCurrentMtx((u32)r[1]);break;
    case GXOP_GXLoadPosMtxImm:gxr_GXLoadPosMtxImm((void*)&r[2],(u32)r[1]);break;
    case GXOP_GXLoadNrmMtxImm:gxr_GXLoadNrmMtxImm((void*)&r[2],(u32)r[1]);break;
    case GXOP_GXLoadTexMtxImm:{GXTexMtxType type=(GXTexMtxType)r[2];(void)type;gxr_GXLoadTexMtxImm((void*)&r[3],(u32)r[1],(GXTexMtxType)r[2]);}break;
    case GXOP_GXSetProjection:gxr_GXSetProjection((void*)&r[2],(GXProjectionType)r[1]);break;
    case GXOP_GXSetProjectionv:gxr_GXSetProjectionv((void*)&r[1]);break;
    case GXOP_GXSetViewport:gxr_GXSetViewport(gx_fifo_float(r[1]),gx_fifo_float(r[2]),gx_fifo_float(r[3]),gx_fifo_float(r[4]),gx_fifo_float(r[5]),gx_fifo_float(r[6]));break;
    case GXOP_GXSetViewportJitter:gxr_GXSetViewportJitter(gx_fifo_float(r[1]),gx_fifo_float(r[2]),gx_fifo_float(r[3]),gx_fifo_float(r[4]),gx_fifo_float(r[5]),gx_fifo_float(r[6]),(u32)r[7]);break;
    case GXOP_GXSetScissor:gxr_GXSetScissor((u32)r[1],(u32)r[2],(u32)r[3],(u32)r[4]);break;
    case GXOP_GXSetCullMode:gxr_GXSetCullMode((GXCullMode)r[1]);break;
    case GXOP_GXSetZMode:gxr_GXSetZMode((GXBool)r[1],(GXCompare)r[2],(GXBool)r[3]);break;
    case GXOP_GXSetBlendMode:gxr_GXSetBlendMode((GXBlendMode)r[1],(GXBlendFactor)r[2],(GXBlendFactor)r[3],(GXLogicOp)r[4]);break;
    case GXOP_GXSetChanMatColor:gxr_GXSetChanMatColor((GXChannelID)r[1],gx_fifo_color(r[2]));break;
    case GXOP_GXSetChanAmbColor:gxr_GXSetChanAmbColor((GXChannelID)r[1],gx_fifo_color(r[2]));break;
    case GXOP_GXSetChanCtrl:gxr_GXSetChanCtrl((GXChannelID)r[1],(GXBool)r[2],(GXColorSrc)r[3],(GXColorSrc)r[4],(u32)r[5],(GXDiffuseFn)r[6],(GXAttnFn)r[7]);break;
    case GXOP_GXSetNumChans:gxr_GXSetNumChans((u8)r[1]);break;
    case GXOP_GXSetNumTexGens:gxr_GXSetNumTexGens((u8)r[1]);break;
    case GXOP_GXSetNumTevStages:gxr_GXSetNumTevStages((u8)r[1]);break;
    case GXOP_GXSetTexCoordGen2:gxr_GXSetTexCoordGen2((GXTexCoordID)r[1],(GXTexGenType)r[2],(GXTexGenSrc)r[3],(u32)r[4],(GXBool)r[5],(u32)r[6]);break;
    case GXOP_GXSetTevOrder:gxr_GXSetTevOrder((GXTevStageID)r[1],(GXTexCoordID)r[2],(GXTexMapID)r[3],(GXChannelID)r[4]);break;
    case GXOP_GXSetTevColorIn:gxr_GXSetTevColorIn((GXTevStageID)r[1],(GXTevColorArg)r[2],(GXTevColorArg)r[3],(GXTevColorArg)r[4],(GXTevColorArg)r[5]);break;
    case GXOP_GXSetTevAlphaIn:gxr_GXSetTevAlphaIn((GXTevStageID)r[1],(GXTevAlphaArg)r[2],(GXTevAlphaArg)r[3],(GXTevAlphaArg)r[4],(GXTevAlphaArg)r[5]);break;
    case GXOP_GXSetTevColorOp:gxr_GXSetTevColorOp((GXTevStageID)r[1],(GXTevOp)r[2],(GXTevBias)r[3],(GXTevScale)r[4],(GXBool)r[5],(GXTevRegID)r[6]);break;
    case GXOP_GXSetTevAlphaOp:gxr_GXSetTevAlphaOp((GXTevStageID)r[1],(GXTevOp)r[2],(GXTevBias)r[3],(GXTevScale)r[4],(GXBool)r[5],(GXTevRegID)r[6]);break;
    case GXOP_GXSetTevSwapMode:gxr_GXSetTevSwapMode((GXTevStageID)r[1],(GXTevSwapSel)r[2],(GXTevSwapSel)r[3]);break;
    case GXOP_GXSetTevKColorSel:gxr_GXSetTevKColorSel((GXTevStageID)r[1],(GXTevKColorSel)r[2]);break;
    case GXOP_GXSetTevKAlphaSel:gxr_GXSetTevKAlphaSel((GXTevStageID)r[1],(GXTevKAlphaSel)r[2]);break;
    case GXOP_GXSetTevOp:gxr_GXSetTevOp((GXTevStageID)r[1],(GXTevMode)r[2]);break;
    case GXOP_GXSetTevColor:gxr_GXSetTevColor((GXTevRegID)r[1],gx_fifo_color(r[2]));break;
    case GXOP_GXSetTevKColor:gxr_GXSetTevKColor((GXTevKColorID)r[1],gx_fifo_color(r[2]));break;
    case GXOP_GXSetColorUpdate:gxr_GXSetColorUpdate((GXBool)r[1]);break;
    case GXOP_GXSetAlphaUpdate:gxr_GXSetAlphaUpdate((GXBool)r[1]);break;
    case GXOP_GXSetDstAlpha:gxr_GXSetDstAlpha((GXBool)r[1],(u8)r[2]);break;
    case GXOP_GXSetDither:gxr_GXSetDither((GXBool)r[1]);break;
    case GXOP_GXSetZCompLoc:gxr_GXSetZCompLoc((GXBool)r[1]);break;
    case GXOP_GXSetAlphaCompare:gxr_GXSetAlphaCompare((GXCompare)r[1],(u8)r[2],(GXAlphaOp)r[3],(GXCompare)r[4],(u8)r[5]);break;
    case GXOP_GXPixModeSync:gxr_GXPixModeSync();break;
    case GXOP_GXLoadTexObj:gxr_GXLoadTexObj((void*)&r[2],(GXTexMapID)r[1]);break;
    case GXOP_GXLoadTlut:gxr_GXLoadTlut((void*)&r[2],(u32)r[1]);break;
    case GXOP_GXLoadLightObjImm:gxr_GXLoadLightObjImm((void*)&r[2],(GXLightID)r[1]);break;
    default:HSD_Panic(__FILE__,__LINE__,"Unknown GX FIFO record");
    }
}
#endif
