"""Generate the GX command FIFO recorders and replay switch (gx_fifo_ops.inc).

Signatures are read from port/engine/gx.c, whose definitions are compiled
as gxr_<name> (GX_FIFO_RENAME below). Every public GX entry point is
classified here: recorded (arguments copied into a FIFO record and replayed
on the translator thread), direct (pure helpers that touch no GX state), or
hand-written in gx_fifo.c (frame boundaries, getters, display lists and the
immediate-mode vertex byte stream). Rerun after changing a GX signature:

    python tools/generate_gx_fifo.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'port/engine/gx.c'
OUTPUT = ROOT / 'port/engine/gx_fifo_ops.h'

# Pure helpers: they only write the caller's object or compute a value.
DIRECT = {'GXInitTexObj', 'GXInitTexObjCI', 'GXInitTexObjLOD', 'GXInitTlutObj', 'GXInitLightColor',
          'GXInitLightDir', 'GXInitLightAttn', 'GXInitLightPos', 'GXInitLightDistAttn', 'GXInitLightSpot',
          'GXInitFogAdjTable', 'GXGetTexBufferSize', 'GXGetTexObjWidth', 'GXGetTexObjHeight', 'GXGetTexObjFmt',
          'GXProject',
          # Boot-time configuration, applied before the translator starts.
          'mp_gx_configure_cache'}
MANUAL = {'GXSetDrawDone', 'GXWaitDrawDone', 'GXDrawDone', 'GXSetDrawDoneCallback', 'GXGetProjectionv',
          'GXGetViewportv', 'GXSetDispCopyYScale', 'mp_gx_left_capture', 'GXCallDisplayList', 'GXInit',
          'mp_gx_write_u8', 'mp_gx_write_s8', 'mp_gx_write_u16', 'mp_gx_write_s16', 'mp_gx_write_u32',
          'mp_gx_write_s32', 'mp_gx_write_f32', 'mp_gx_write_u64', 'mp_gx_write_s64', 'mp_gx_write_f64'}
# Pointer arguments recorded by address: the translator reads them later,
# exactly as the GameCube GPU read display lists, arrays and copy targets.
BY_ADDRESS = {('GXSetArray', 'p'), ('GXCopyDisp', 'dest'), ('GXCopyTex', 'dest'),
              ('mp_gx_copy_texture_only', 'dest'), ('mp_gx_copy_clear_only', 'dest'),
              ('mp_gx_source_write', 'p')}
# Pointer arguments whose contents are copied into the record (words).
# 'type' entries depend on another argument; None marks a nullable pointer.
BLOBS = {('GXLoadPosMtxImm', 'm'): 12, ('GXLoadNrmMtxImm', 'm'): 12,
         ('GXLoadTexMtxImm', 'm'): 'type==GX_MTX2x4?8:12', ('GXSetProjection', 'm'): 16,
         ('GXSetProjectionv', 'p'): 7, ('GXSetIndTexMtx', 'm'): 6,
         ('GXLoadTexObj', 'o'): 'sizeof(GXTexObj)/4', ('GXLoadTlut', 'o'): 'sizeof(GXTlutObj)/4',
         ('GXLoadLightObjImm', 'o'): 'sizeof(GXLightObj)/4'}
NULLABLE = {('GXSetFogRangeAdj', 't'): 'sizeof(GXFogAdjTable)', ('GXSetCopyFilter', 'p'): '24',
            ('GXSetCopyFilter', 'f'): '7'}
# Main-thread mirrors for state that GX getters return.
MIRROR = {'GXSetProjection', 'GXSetProjectionv', 'GXSetViewport', 'GXSetViewportJitter', 'GXSetDispCopySrc'}


def signatures():
    text = SOURCE.read_text(encoding='utf-8')
    found = {}
    pattern = r'(?:^|[;}])\s*((?:const\s+)?[A-Za-z_][A-Za-z0-9_]*\s*\**)\s*((?:GX|mp_gx_)[A-Za-z0-9_]*)\s*\(([^)]*)\)\s*\{'
    for m in re.finditer(pattern, text, re.M):
        ret, name, params = m.group(1).strip(), m.group(2), m.group(3).strip()
        found.setdefault(name, (ret, params))
    return found


def split_params(params):
    if params in ('', 'void'): return []
    out = []
    for p in params.split(','):
        p = p.strip()
        m = re.match(r'(.*?)([A-Za-z_][A-Za-z0-9_]*)\s*((?:\[[^\]]*\])*)$', p)
        ptype, pname, dims = m.group(1).strip(), m.group(2), m.group(3)
        out.append((ptype, pname, dims, p))
    return out


def main():
    sigs = signatures()
    lines = ['/* Generated by tools/generate_gx_fifo.py from port/engine/gx.c. Do not edit. */']
    protos, records, cases, ops = [], [], [], []
    for name, (ret, params) in sigs.items():
        plist = split_params(params)
        protos.append(f'{ret} gxr_{name}({params if params else "void"});')
        if name in MANUAL:
            continue
        call_args = ','.join(p[1] for p in plist)
        if name in DIRECT:
            body = f'{"return " if ret != "void" else ""}gxr_{name}({call_args});'
            records.append(f'{ret} {name}({params if params else "void"}){{{body}}}')
            continue
        if ret != 'void':
            raise SystemExit(f'{name}: recorded function returns {ret}')
        op = 'GXOP_' + name
        ops.append(op)
        scalars, blobs, store, load = [], [], [], []
        index = 1
        for ptype, pname, dims, raw in plist:
            key = (name, pname)
            if key in BLOBS or key in NULLABLE:
                blobs.append((ptype, pname, dims, raw))
                continue
            if '*' in ptype or dims:
                if key not in BY_ADDRESS:
                    raise SystemExit(f'{name}: unclassified pointer parameter {raw}')
                store.append(f'gx_r[{index}]=(u32){pname};')
                load.append(f'({ptype})r[{index}]')
                index += 1
            elif ptype in ('float', 'f32'):
                store.append(f'memcpy(&gx_r[{index}],&{pname},4);')
                load.append(f'gx_fifo_float(r[{index}])')
                index += 1
            elif ptype == 'GXColor':
                store.append(f'memcpy(&gx_r[{index}],&{pname},4);')
                load.append(f'gx_fifo_color(r[{index}])')
                index += 1
            elif ptype == 'GXColorS10':
                store.append(f'memcpy(&gx_r[{index}],&{pname},8);')
                load.append(f'gx_fifo_color_s10(&r[{index}])')
                index += 2
            elif ptype in ('double', 'u64', 's64'):
                raise SystemExit(f'{name}: 64-bit parameter {raw}')
            else:
                store.append(f'gx_r[{index}]=(u32){pname};')
                load.append(f'({ptype})r[{index}]')
                index += 1
            scalars.append(pname)
        size_terms, blob_store, blob_load = [str(index)], [], {}
        offset_expr = str(index)
        for ptype, pname, dims, raw in blobs:
            key = (name, pname)
            if key in BLOBS:
                words = str(BLOBS[key])
                size_terms.append(f'({words})')
                blob_store.append(f'memcpy(&gx_r[{offset_expr}],{pname},({words})*4);')
                blob_load[pname] = f'(void*)&r[{offset_expr}]'
                offset_expr = f'{offset_expr}+({words})'
            else:
                bytes_ = NULLABLE[key]
                words = f'((({bytes_})+3)/4)'
                size_terms.append(f'1+{words}')
                blob_store.append(f'gx_r[{offset_expr}]={pname}!=0;if({pname})memcpy(&gx_r[{offset_expr}+1],{pname},{bytes_});')
                blob_load[pname] = f'(r[{offset_expr}]?(void*)&r[{offset_expr}+1]:(void*)0)'
                offset_expr = f'{offset_expr}+1+{words}'
        size = '+'.join(size_terms)
        mirror = f'gx_mirror_{name}({call_args});' if name in MIRROR else ''
        records.append(
            f'void {name}({params if params else "void"}){{{mirror}\n'
            f'    if(!mp_gx_async){{gxr_{name}({call_args});return;}}\n'
            f'    unsigned gx_words={size};u32*gx_r=gx_fifo_begin(gx_words);\n'
            f'    {"".join(store)}{"".join(blob_store)}\n'
            f'    gx_fifo_end(gx_r,{op},gx_words);\n}}')
        # Replay arguments in declaration order.
        args, li = [], 0
        for ptype, pname, dims, raw in plist:
            if pname in blob_load:
                args.append(blob_load[pname])
            else:
                args.append(load[li]); li += 1
        # Blob loads referencing other arguments (type) must see replayed values.
        replay = f'gxr_{name}({",".join(args)});'
        if any(re.search(r'\btype\b', str(BLOBS.get((name, p[1]), ''))) for p in plist):
            replay = f'{{GXTexMtxType type=(GXTexMtxType)r[2];(void)type;{replay}}}'
        cases.append(f'    case {op}:{replay}break;')
    lines.append('#ifndef MP_GX_FIFO_OPS_H')
    lines.append('#define MP_GX_FIFO_OPS_H')
    lines.append('enum{GXOP_WRAP=1,GXOP_BYTES,GXOP_FRAME_END,GXOP_STEREO,GXOP_LIST,GXOP_LIST_INLINE,GXOP_DC_RANGE,')
    lines.append('    GXOP_INIT,GXOP_LEFT_CAPTURE,GXOP_COPY_YSCALE,')
    lines.append('    ' + ',\n    '.join(ops) + ',GXOP_COUNT};')
    lines.extend(protos)
    lines.append('#endif')
    lines.append('/* gx.c compiles every entry point as its replay implementation. */')
    lines.append('#ifdef GX_FIFO_RENAME')
    lines.extend(f'#define {name} gxr_{name}' for name in sigs)
    lines.append('#endif')
    lines.append('#ifdef GX_FIFO_RECORDERS')
    lines.extend(records)
    lines.append('static void gx_replay_generated(unsigned op,const u32*r){\n    switch(op){')
    lines.extend(cases)
    lines.append('    default:HSD_Panic(__FILE__,__LINE__,"Unknown GX FIFO record");\n    }\n}')
    lines.append('#endif')
    OUTPUT.write_text('\n'.join(lines) + '\n', encoding='utf-8', newline='\n')
    print(f'{len(ops)} recorded, {len(DIRECT)} direct, {len(MANUAL)} manual of {len(sigs)} entry points -> {OUTPUT}')


if __name__ == '__main__':
    main()
