"""Generate GX matrix palettes, two lighting channels and affine materials."""
from pathlib import Path
import argparse
ROOT=Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument('--output',type=Path,default=ROOT/'port/3ds')
parser.add_argument('--reference',action='store_true',help='Emit the preceding shader for development comparisons')
parser.add_argument('--schedule-lighting',action='store_true',help='Explicitly select the current lighting schedule (also the default)')
parser.add_argument('--legacy-lighting-schedule',action='store_true',help='Reproduce the earlier uniform-predicate candidate for comparisons')
parser.add_argument('--identity-affine',action='store_true',help='Development candidate: short primary-color path selected by negative config[0].x')
parser.add_argument('--unlit-affine',action='store_true',help='Development candidate: reuse an inactive lighting boolean only on the unlit path')
args=parser.parse_args()
if args.reference and args.schedule_lighting:parser.error('--reference cannot include candidate changes')
if args.schedule_lighting and args.legacy_lighting_schedule:parser.error('Choose only one lighting schedule')
if args.identity_affine and (args.reference or args.legacy_lighting_schedule):parser.error('Identity affine requires the current lighting schedule')
if args.unlit_affine and (args.reference or args.legacy_lighting_schedule or args.identity_affine):parser.error('Unlit affine requires the current schedule and is separate from identity affine')
args.schedule_lighting=not (args.reference or args.legacy_lighting_schedule)
args.output.mkdir(parents=True,exist_ok=True)
shader='''; Generated by tools/generate_vertex_shader.py; layout: gpu_vertex.h.
.fvec model[30], normal[30], projection[4], lightpos[4], lightdir[4], lightcolor[4]
.fvec attenuation[4], cosattenuation[4], shade[5], ambient[2], config[2], material1, finalclamp
.constf constants(0.0,1.0,0.000000000001,2.0)
.alias zeros constants.xxxx
.alias ones constants.yyyy
.out outpos position
.out outcolor color
.out outtex texcoord0
.proc main
    mov r0, v3.wwww
    cmp zeros, le, le, r0.x
    ifc cmp.x
        mova a0.x, r0.x
        dp4 r1.x, model[a0.x], v0
        dp4 r1.y, model[a0.x+1], v0
        dp4 r1.z, model[a0.x+2], v0
        mov r1.w, ones
        dp4 outpos.x, projection[0], r1
        dp4 outpos.y, projection[1], r1
        dp4 outpos.z, projection[2], r1
        dp4 outpos.w, projection[3], r1
        mov r0, config[0]
        mov r3, config[1]
        add r0.x, r0.x, r3.x
        cmp zeros, lt, lt, r0.x
        ifc cmp.x
            dp3 r2.x, normal[a0.x], v3
            dp3 r2.y, normal[a0.x+1], v3
            dp3 r2.z, normal[a0.x+2], v3
            dp3 r3.x, r2, r2
            max r3.x, constants.z, r3.x
            rsq r3.x, r3.x
            mul r2.xyz, r2, r3.x
        .end
        mov r4, ambient[0]
        mov r14, ambient[1]
'''
for i in range(4):
    shader+=f'''        mov r5, lightcolor[{i}]
        cmp zeros, lt, lt, r5.w
        ifc cmp.x
            cmp ones, lt, lt, r5.w
            ifc cmp.x
                mov r0, config[1]
            .else
                mov r0, config[0]
            .end
            mov r6, lightpos[{i}]
            mad r6.xyz, -r1, r6.w, r6
            dp3 r3.x, r6, r6
            max r3.x, constants.z, r3.x
            rsq r3.y, r3.x
            mul r6.xyz, r6, r3.y
            mul r3.z, r3.x, r3.y
            dp3 r8.x, r2, r6
            mov r8.w, ones
            cmp constants.w, gt, gt, r0.w
            ifc cmp.x
                mov r9, lightdir[{i}]
                mov r10.x, ones
                cmp zeros, eq, eq, r0.w
                ifc cmp.x
                    dp3 r10.y, r2, r9
                    max r10.y, zeros, r10.y
                    mov r13, zeros
                    sge r13.x, r8.x, r13.x
                    mul r10.y, r10.y, r13.x
                    mul r10.z, r10.y, r10.y
                    dp3 r8.z, attenuation[{i}], r10
                .else
                    dp3 r10.y, r6, r9
                    max r10.y, zeros, r10.y
                    mul r10.z, r10.y, r10.y
                    mov r12.x, ones
                    mov r12.y, r3.z
                    mov r12.z, r3.x
                    dp3 r8.z, attenuation[{i}], r12
                .end
                dp3 r8.y, cosattenuation[{i}], r10
                max r8.y, zeros, r8.y
                cmp zeros, lt, lt, r8.z
                ifc cmp.x
                    rcp r8.w, r8.z
                    mul r8.w, r8.w, r8.y
                .else
                    mov r8.w, zeros
                .end
            .end
            max r9.x, zeros, r8.x
            add r9.x, r9.x, -r8.x
            mad r8.x, r0.z, r9.x, r8.x
            add r9.x, ones, -r8.x
            mad r8.x, r0.y, r9.x, r8.x
            mul r8.x, r8.x, r8.w
            cmp ones, lt, lt, r5.w
            ifc cmp.x
                mad r14.xyz, r5, r8.x, r14
            .else
                mad r4.xyz, r5, r8.x, r4
            .end
        .end
'''
shader+='''        mov r10, zeros
        sge r9, v4, r10
        max r10, zeros, v4
        add r7, r10, -v1
        mad r7, r9, r7, v1
        mov r15, material1
        mov r0, config[0]
        cmp zeros, lt, lt, r0.x
        ifc cmp.x
            max r4.xyz, zeros, r4
            min r4.xyz, ones, r4
            mul r7.xyz, r7, r4
        .end
        mov r0, config[1]
        cmp zeros, lt, lt, r0.x
        ifc cmp.x
            max r14.xyz, zeros, r14
            min r14.xyz, ones, r14
            mul r15.xyz, r15, r14
        .end
        mul r8, shade[1], r7
        mov r9, shade[2]
        mad r8, r9, r7.w, r8
        mov r9, shade[3]
        mad r8, r9, r15, r8
        mov r9, shade[4]
        mad r8, r9, r15.w, r8
        add r8, shade[0], r8
        max r9, zeros, r8
        min r9, ones, r9
        add r9, r9, -r8
        mov r10, finalclamp
        mad outcolor, r10, r9, r8
    .else
        mov outpos, v0
        mov outcolor, v1
    .end
    mov outtex.xy, v2
    mov outtex.z, zeros
    mov outtex.w, ones
    end
.end
'''
# Early specialized entry paths keep the original full shader's IF nesting
# unchanged. PICA has only a small flow-control stack. Mixed CPU/GPU batches
# first reject the CPU clip-space marker before taking either shortcut.
transform=('    mov r0, v3.wwww\n    cmp zeros, le, le, r0.x\n'
    '    jmpc !cmp.x, full_vertex\n'+shader[shader.index('        mova a0.x'):shader.index('        mov r0, config[0]')])
material=shader[shader.index('        mov r10, zeros\n        sge r9, v4'):shader.index('        mul r8, shade[1]')]
# Omit the two lighting-channel clamps from the unlit path.
material=material[:material.index('        mov r0, config[0]')]
affine=shader[shader.index('        mul r8, shade[1]'):shader.index('    .else\n        mov outpos, v0')]
tex=shader[shader.index('    mov outtex.xy'):shader.index('    end\n.end')]
shader=shader.replace('.alias zeros constants.xxxx',
    '.bool constant_color, unlit_color\n.alias zeros constants.xxxx')
shader=shader.replace('.proc main\n', '.proc main\n'
    '    jmpu constant_color, flat_vertex\n    jmpu unlit_color, unlit_vertex\nfull_vertex:\n')
shader=shader.replace('    end\n.end', '    end\nflat_vertex:\n'+transform+
    '        mov r8, zeros\n        add outcolor, shade[0], r8\n'+tex+'    end\nunlit_vertex:\n'+transform+
    material+affine+tex+'    end\n.end')
if not args.reference:
    # These predicates depend only on draw uniforms. The CPU supplies their
    # exact enum/boolean decisions once per draw; all per-vertex arithmetic
    # and the depth of the PICA flow-control stack remain unchanged.
    names=[*(f'light{i}_active' for i in range(4)),
           *(f'light{i}_channel1' for i in range(4)),
           *(f'light{i}_attenuate' for i in range(4)),
           'channel0_lit','channel1_lit']
    shader=shader.replace('.bool constant_color, unlit_color',
                          '.bool constant_color, unlit_color, '+', '.join(names))
    for i in range(4):
        begin=shader.index(f'        mov r5, lightcolor[{i}]')
        end=shader.index('        mov r5, lightcolor[',begin+1) if i<3 else shader.index('        mov r10, zeros',begin)
        body=shader[begin:end]
        body=body.replace(f'        mov r5, lightcolor[{i}]\n        cmp zeros, lt, lt, r5.w\n        ifc cmp.x',
                          f'        ifu light{i}_active\n            mov r5, lightcolor[{i}]')
        assert body.count('            cmp ones, lt, lt, r5.w\n            ifc cmp.x')==2
        body=body.replace('            cmp ones, lt, lt, r5.w\n            ifc cmp.x',f'            ifu light{i}_channel1')
        body=body.replace('            cmp constants.w, gt, gt, r0.w\n            ifc cmp.x',f'            ifu light{i}_attenuate')
        shader=shader[:begin]+body+shader[end:]
    for ch in range(2):
        pattern=f'        mov r0, config[{ch}]\n        cmp zeros, lt, lt, r0.x\n        ifc cmp.x'
        assert shader.count(pattern)==1
        shader=shader.replace(pattern,f'        ifu channel{ch}_lit')
if args.schedule_lighting:
    # Dispatch reaches full_vertex only when at least one channel is lit.
    # The forced-full test path may have neither channel lit; in that case
    # its normalized normal is unused, so computing it is harmless too.
    # Keep the normal arithmetic identical, including the zero-length floor.
    guard='''        mov r0, config[0]
        mov r3, config[1]
        add r0.x, r0.x, r3.x
        cmp zeros, lt, lt, r0.x
        ifc cmp.x
'''
    normal='''            dp3 r2.x, normal[a0.x], v3
            dp3 r2.y, normal[a0.x+1], v3
            dp3 r2.z, normal[a0.x+2], v3
            dp3 r3.x, r2, r2
            max r3.x, constants.z, r3.x
            rsq r3.x, r3.x
            mul r2.xyz, r2, r3.x
'''
    assert shader.count(guard+normal+'        .end\n')==1
    shader=shader.replace(guard+normal+'        .end\n',normal)
    # r3.z is the distance, used only by GX_AF_SPOT. SPEC uses the squared
    # normal/light dot and NONE uses no attenuation. r3.x/y are unchanged
    # between normalization and this use; do not reorder the dot products.
    assert shader.count('            mul r3.z, r3.x, r3.y\n')==4
    shader=shader.replace('            mul r3.z, r3.x, r3.y\n','')
    use='                    mov r12.y, r3.z\n'
    assert shader.count(use)==4
    shader=shader.replace(use,'                    mul r3.z, r3.x, r3.y\n'+use)
if args.identity_affine:
    assert shader.count(affine)==2
    shader=shader.replace(affine,
        '        mov r10, config[0]\n        cmp zeros, gt, gt, r10.x\n        ifc cmp.x\n'
        '            max r8, zeros, r7\n            min outcolor, ones, r8\n'
        '        .else\n'+affine+'        .end\n')
    shader='; MP_AFFINE_IDENTITY_SHADER\n'+shader
if args.unlit_affine:
    begin=shader.index('\nunlit_vertex:\n')
    path=shader[begin:]
    assert path.count('        mov r15, material1\n')==1
    # b2 is light0_active in full_vertex. The unlit path reads no lighting
    # state, so it can use that same bit for this exact material predicate.
    # CPU clip-space markers have already returned through full_vertex.
    path=path.replace('        mov r15, material1\n',
        '        jmpu light0_active, unlit_primary_color\n        mov r15, material1\n')
    path=path.replace('    end\n.end', '    end\nunlit_primary_color:\n'
        '        max r8, zeros, r7\n        min outcolor, ones, r8\n'+tex+'    end\n.end')
    shader='; MP_UNLIT_AFFINE_SHADER\n'+shader[:begin]+path
(args.output/'vertex.v.pica').write_text(shader)
# A separate program leaves the common single-texture vertex shader unchanged.
dual=shader.replace('.out outtex texcoord0','.out outtex texcoord0\n.out outtex1 texcoord1')
dual=dual.replace('    end\n','    mov outtex1.xy, v5\n    mov outtex1.z, zeros\n    mov outtex1.w, ones\n    end\n')
(args.output/'vertex-dual.v.pica').write_text(dual)
# Stereo adjusts the rotated horizontal clip coordinate on every exit;
# fixed attribute 6 holds (scale,bias). All routes share identical uniforms.
for name,source in [('vertex-stereo',shader),('vertex-dual-stereo',dual)]:
    assert 'r11' not in source
    stereo=source.replace('outpos', 'r11').replace('.out r11 position','.out outpos position')
    stereo=stereo.replace('    end\n','    mad r11.y, v6.x, r11.w, r11.y\n    add r11.y, r11.y, v6.y\n    mov outpos, r11\n    end\n')
    (args.output/f'{name}.v.pica').write_text(stereo)
# The expensive CPU fallback is affine -> clamp -> affine. Separate programs
# add only its final multiply/add, using fixed attributes rather than exceeding
# the PICA uniform bank. Keep all normal shader binaries unchanged.
if not (args.reference or args.identity_affine or args.unlit_affine):
    for stem in ('vertex','vertex-dual','vertex-stereo','vertex-dual-stereo'):
        source=(args.output/f'{stem}.v.pica').read_text()
        old='        mad outcolor, r10, r9, r8\n'
        assert source.count(old)==2
        source=source.replace(old,'        mad r8, r10, r9, r8\n        mul r8, v7, r8\n        add outcolor, r8, v8\n')
        (args.output/f'{stem}-clamped.v.pica').write_text('; Clamped material program: fixed v7 scale and v8 bias.\n'+source)
